### PR TITLE
create directories before creating archive file

### PR DESCRIPTION
**Pull request by bugbuilder**
avoid deadlock/panic

### CODE REVIEW

**Comment by donny-dont** [comment]
Can you explain what it is you're seeing? The tar code for example will create the directory structure, https://github.com/drone/drone-cache-lib/blob/master/archive/tar/tar.go#L146-L151, so I'm not sure what it is that is being solved with this.

**Comment by bugbuilder** [comment]
Hi @donny-dont 
When [drone-volume-cache](https://github.com/drone-plugins/drone-volume-cache/) try to save the tar file in the rebuild process, its will fail if the path doesn't exist, this plugin use a [path convention](https://github.com/drone-plugins/drone-volume-cache/blob/master/main.go#L114-L127), in that case the use of repo-owner/repo-name/file.tar will cause a deadlock. 

More detail in this [issue](https://github.com/drone-plugins/drone-volume-cache/issues/2)

**Comment by bugbuilder** [comment]
**output**
```
time="2017-08-21T19:00:02Z" level=info msg="Rebuilding cache at /cache/bugbuilder/test/master.tar" 
time="2017-08-21T19:00:02Z" level=info msg="Rebuilding cache at [./repository] to /cache/bugbuilder/test/master.tar" 
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:

github.com/drone-plugins/drone-volume-cache/vendor/github.com/drone/drone-cache-lib/cache.rebuildCache(0xc4200704d0, 0x1, 0x1, 0xc420076300, 0x21, 0x61b880, 0x649f20, 0x61ad80, 0x649f20, 0x0, ...)
	/home/bugbuilder/go/src/github.com/drone-plugins/drone-volume-cache/vendor/github.com/drone/drone-cache-lib/cache/cache.go:86 +0x3a7
github.com/drone-plugins/drone-volume-cache/vendor/github.com/drone/drone-cache-lib/cache.Cache.Rebuild(0x61b880, 0x649f20, 0x61ad80, 0x649f20, 0xc4200704d0, 0x1, 0x1, 0xc420076300, 0x21, 0xc420076330, ...)
	/home/bugbuilder/go/src/github.com/drone-plugins/drone-volume-cache/vendor/github.com/drone/drone-cache-lib/cache/cache.go:28 +0x91
main.(*plugin).Exec(0xc4200ad7d0, 0x2, 0x2)
	/home/bugbuilder/go/src/github.com/drone-plugins/drone-volume-cache/plugin.go:33 +0x55a
main.run(0xc4200a4000, 0xc4200a4000, 0xc42003b857)
	/home/bugbuilder/go/src/github.com/drone-plugins/drone-volume-cache/main.go:140 +0x40d
github.com/drone-plugins/drone-volume-cache/vendor/github.com/urfave/cli.HandleAction(0x541a00, 0x579430, 0xc4200a4000, 0xc42006e4e0, 0x0)
	/home/bugbuilder/go/src/github.com/drone-plugins/drone-volume-cache/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/drone-plugins/drone-volume-cache/vendor/github.com/urfave/cli.(*App).Run(0xc420056d00, 0xc420070130, 0x1, 0x1, 0x0, 0x0)
	/home/bugbuilder/go/src/github.com/drone-plugins/drone-volume-cache/vendor/github.com/urfave/cli/app.go:259 +0x70d
main.main()
	/home/bugbuilder/go/src/github.com/drone-plugins/drone-volume-cache/main.go:100 +0xaff
```

**Comment by bugbuilder** [comment]
We could change [drone-volume-cache](https://github.com/drone-plugins/drone-volume-cache/blob/master/main.go#L114-L127) to do the same that [cncd/pipeline](https://github.com/cncd/pipeline/blob/master/pipeline/frontend/yaml/compiler/cacher.go#L55) does. In that way we avoid this deadlock and we don't have to change this library. What do you think @donny-dont 
?

**Pull request closed without merging**
